receivers:
  otlp:
    protocols:
      http:
      grpc:
        endpoint: 0.0.0.0:4317
  filelog/jicofo:
    include: ['/tmp/jitsi-logs/jicofo.log']
    operators:
      - type: regex_parser
        regex: "^(?P<app>Jicofo) (?P<timestamp>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3}) (?P<level>\\w+): \\[(?P<pid>\\d+)\\] (?P<message>[\\S\\s]*)$"
  filelog/jvb:
    include: ['/tmp/jitsi-logs/jvb.log']
    operators:
      - type: regex_parser
        regex: "^(?P<app>JVB) (?P<timestamp>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3}) (?P<level>\\w+): \\[(?P<pid>\\d+)\\] (?P<message>[\\S\\s]*)$"        
processors:
  batch:

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    logs/jicofo:
      receivers: [otlp, filelog/jicofo]
      processors: [batch]
      exporters: [loki]
    logs/jvb: 
      receivers: [otlp, filelog/jvb]
      processors: [batch]
      exporters: [loki]
